#pragma once
#include "Service.h" 
#include "Employee.h" 
#include "Client.h" 
#include <vector> 
#include <Windows.h> 
#include <iomanip> 
bool InputEmployeeInfo(); 
bool InputClientInfo(); 
bool InputAllInfo(); 
bool AllInfoTable(); 
bool AppendPeople(); 
bool RemoveStorTc(); 
bool Sort(); 
bool picture(); 
bool Sqrt25(); 
bool meeting(); 
void ServiceAboutTable();
void InputServiceInfo(); 
bool EmployeesTable(); 
bool CheckAge(); 
void ClientsTable(); 
void CalcService(); 
void LocalInformation(); 
